name: Deploy Docs

on:
  push:
    tags:
      - 'docs-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false  # important

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set git remote with token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Install deps
        run: pip install mkdocs mkdocs-material mike

      - name: Deploy docs
        run: mike deploy ${GITHUB_REF_NAME#docs-} latest --push
